version: "3.8"

services:
  streamlit-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      # Set your remote backend URL here
      - API_URL=http://localhost:8000
    volumes:
      # Mount the app file for development (optional - remove for production)
      - ./streamlit_app.py:/app/streamlit_app.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
