apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-image-frontend
  labels:
    app: qwen-image-frontend
spec:
  selector:
    matchLabels:
      app: qwen-image-frontend
  template:
    metadata:
      labels:
        app: qwen-image-frontend
    spec:
      containers:
      - name: streamlit
        image: 985955614379.dkr.ecr.us-west-2.amazonaws.com/image-gen-streamlit:latest
        ports:
        - name: http
          containerPort: 8501
        env:
        - name: API_URL
          value: "http://your-backend-service:8000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qwen-image-frontend-service
spec:
  selector:
    app: qwen-image-frontend
  ports:
  - port: 80
    targetPort: http
  type: ClusterIP
