apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-vl
  labels:
    app: qwen-vl
    engine: vllm
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qwen-vl
      engine: vllm
  template:
    metadata:
      labels:
        app: qwen-vl
        engine: vllm
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: g6e.2xlarge
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: model
          image: vllm/vllm-openai:latest
          command: ["vllm", "serve"]
          args:
            - "Qwen/Qwen2.5-VL-7B-Instruct"
            - "--host=0.0.0.0"
            - "--port=8000"
            - '--limit-mm-per-prompt={"image":2,"video":1}'
          ports:
            - name: http
              containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /root/.cache/huggingface
              name: cache-volume
            - name: shm
              mountPath: /dev/shm
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 5
          startupProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 60
      volumes:
        - name: cache-volume
          hostPath:
            path: /mnt/k8s-disks/0/models/qwen-vl
            type: DirectoryOrCreate
        # vLLM needs to access the host's shared memory for tensor parallel inference.
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "20Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: qwen-vl
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: qwen-vl
    engine: vllm
  type: ClusterIP
# vllm serve Qwen/Qwen2.5-VL-7B-Instruct  \
#   --host 0.0.0.0 \
#   --port 8000 \
#   --data-parallel-size 4 \
#   --limit-mm-per-prompt '{"image":2,"video":0}'
